name: End to End

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        ghc: ["8.8.4"]
        spec:
          - "0.16.1"
        node:
          - 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: NPM install
        run: npm install

      - name: Setup dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.25.0"

      - name: Install dfx
        run: |
          dfx start --clean --background

      - name: mops install
        run: |
          npm install -g ic-mops
          mops install

      - name: Build all canisters
        run: |
          dfx deploy
          dfx stop